attention_dropout: 0.1
batch_size: 8
betas:
- 0.9
- 0.999
checkpoints_path: null
clip_grad: 0.25
deterministic_torch: false
embedding_dim: 256
embedding_dropout: 0.1
env_name: "walker2d-medium-replay-v2"
episode_len: 1000
eval_episodes: 24
eval_every: 5000
eval_seed: 42
learning_rate: 0.0001
max_action: 1.0
num_heads: 8
n_traj_max: 4
num_layers: 4
num_workers: 4
project: "ORDER"
group: "AT-walker-last-eval"
name: "AT-long-8gpu-eval-last"
residual_dropout: 0.1
reward_scale: 0.001
target_returns: [5000.0]
train_seed: 10
update_steps: 100000
warmup_steps: 10000
weight_decay: 0.0001